### PR TITLE
Optimise performance a little

### PR DESCRIPTION
**Pull request by lpil**
Hello! I've moved to string patterns and removed any repeat traversals of already traversed input. It has resulted in a decent performance improvement:
```
Name           ips        average  deviation         median         99th %
new           0.29         3.44 s     ±1.17%         3.44 s         3.47 s
old          0.178         5.62 s     ±4.48%         5.62 s         5.80 s

Comparison: 
new           0.29
old          0.178 - 1.63x slower +2.18 s

Memory usage statistics:

Name    Memory usage
new         39.32 MB
old         57.36 MB - 1.46x memory usage +18.04 MB

**All measurements for memory usage were the same**

Reduction count statistics:

Name         average  deviation         median         99th %
new           1.94 M     ±0.04%         1.94 M         1.94 M
old           3.80 M     ±0.00%         3.80 M         3.80 M

Comparison: 
new           1.94 M
old           3.80 M - 1.96x reduction count +1.87 M
```

I've left the benchmark code there if you want to try it, but lmk and I can remove it.

### CODE REVIEW

**Comment by DanielleMaywood** [comment]
If you add the following test:

```gleam
pub fn names_that_begin_with_a_keyword_test() {
  "let_statement"
  |> glexer.new()
  |> glexer.lex()
  |> should.equal([#(token.Name("let_statement"), Position(0))])
}
```

The change fails this test, parsing it as `[Let(Position(0)), #(DiscardName("statement"), Position(3))]`.

**Comment by lpil** [comment]
Well spotted! Thank you

**Comment by DanielleMaywood** [comment]
Looks good! 

Regarding the benchmarking code, I definitely think there is value in having a benchmark however I'm unsure how we could continue to have a meaningful one without having to constantly update `tests/glexer_old.gleam`.

**Comment by lpil** [comment]
You always have to copy/paste the previous version to a new file when benchmarking I'm afraid.

**Pull request merged**
